### ISSUE TITLE
Set Dependabot Commit Message Prefixes

### ISSUE THREAD

**Issue by davidlday** [prosegrinder/.github#35]
- [ ] python-pointofview
- [ ] python-narrative
- [ ] python-cmudict
- [ ] python-syllables
- [ ] python-prosegrinder
- [ ] python-prosegrinder-restapi
- [ ] annotatedtext
- [ ] annotatedtext-remark
- [ ] annotatedtext-rehype
- [ ] languagetool-service

For References:

`github-actions`
```yaml
    commit-message:
      prefix: "ci"
      include: "scope"
```

 `gitsubmodule`
```yaml
    commit-message:
      prefix: "build"
      include: scope
```

`pip\node\etc`
```yaml
    commit-message:
      prefix: "patch"
      prefix-development: "build"
      include: "scope"
```
